application:
  name: AIgenda
  version: 0.1.0
  description: Plugin for managing your day to day activities

springdoc:
  api-docs:
    path: /openapi

security:
  enabled: false

spring:
  profiles:
    include: github

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    root: info
