name: upload-dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Dependencies-submission
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-configuration-mapping: |-
            :core|compileClasspath
          gradle-build-module: |-
            :core
          sub-module-mode: 'INDIVIDUAL_DEEP'
          include-build-environment: true