name: upload-dependencies

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dependencies-submission
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          use-gradlew: true
          gradle-project-path: .